import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import ProductCard from '../components/ProductCard';

const Home: NextPage = () => {
	return (
		<div className='bg-cream w-full h-screen'>
			<Head>
				<title>Product Preview</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ProductCard />
		</div>
	);
};

export default Home;
